# Generated by Django 3.2.12 on 2022-03-07 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_classroom_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentclassroom',
            old_name='classoom',
            new_name='classroom',
        ),
        migrations.RenameField(
            model_name='teacherclassroom',
            old_name='classoom',
            new_name='classroom',
        ),
    ]
