# Generated by Django 4.0.3 on 2022-03-21 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0003_auto_20220307_0624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('points', models.IntegerField()),
                ('assigned', models.DateField(auto_now=True)),
                ('due', models.DateTimeField(null=True)),
                ('slug', models.SlugField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.classroom')),
            ],
        ),
    ]
