# Generated by Django 4.0.5 on 2022-06-13 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0002_file_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='points',
            field=models.IntegerField(null=True),
        ),
    ]
